### ISSUE TITLE
Editing created contacts doesn't work in latest versions.

### ISSUE THREAD

**Issue by nxsm** [iansullivan88/desktop-phone-list#1]
I noticed that after creating a contact, editing it is not possible anymore since v.0.12.
Clicking the button wont do anything. 
 I am not sure what exactly changed in newest version. Any ideas?

**Comment by iansullivan88** [comment]
I just tried it on my machine. It was trying to save the list of contacts straight to c:. I have made a slight change so it goes back to saving in the user's home directory. Let me know how you get on.
Cheers
Ian

**Comment by nxsm** [comment]
Thanks for reply. 
It was saving into my user's home directory before. It's just, clicking on `<a href='#/contact/{{contact.id}}'` , wont redirect me back to editing page as it normally does in nw.js v.0.12. On v.0.13 doesn't work.
While clicking on `<a id="add" href='#/contact/'>` sucessfully redirects me to add new contact.

**Comment by iansullivan88** [comment]
Ah, there was a second issue! Does it work for you now?
Ian

**Comment by nxsm** [comment]
It works now.  You are the best. Thanks :)

**Comment by iansullivan88** [comment]
Thanks, you are welcome!
